//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVC001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public long StaffId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<double> PhoneNumber { get; set; }
        public string EmailId { get; set; }
        public string RFID { get; set; }
        public string ORGID { get; set; }
        public string Dept { get; set; }
    }
}
