//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVC001.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public long StudentId { get; set; }

        [Required]
        [Display(Name = "First Name")]
        [StringLength(255, MinimumLength = 2)]
        public string StudentFirstName { get; set; }

        [Required]
        [Display(Name = "Middle Name")]
        [StringLength(255, MinimumLength = 2)]
        public string StudentMiddleName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        [StringLength(255, MinimumLength = 2)]
        public string StudentLastName { get; set; }


        public string Class { get; set; }
        public string Section { get; set; }

        [Required]
        [StringLength(1)]
        public string Gender { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateOfBirth { get; set; }

        [Required]
        [Display(Name = "RFID #")]
        [RegularExpression(@"\d{6,20}")]
        public string RFID { get; set; }

        [Required]
        [Display(Name = "Parent First Name")]
        [StringLength(255, MinimumLength = 2)]
        public string ParentFirstName { get; set; }

        [Display(Name = "Parent Middle Name")]
        [StringLength(255, MinimumLength = 2)]
        public string ParentMiddleName { get; set; }

        [Required]
        [Display(Name = "Parent Last Name")]
        [StringLength(255, MinimumLength = 2)]
        public string ParentLastName { get; set; }

        [Required]
        [Display(Name = "Parent Phone Number")]
        //[RegularExpression(@"\d")]
        [DataType(DataType.PhoneNumber)]
        public Nullable<double> ParentPrimaryPhoneNumber { get; set; }

        [Display(Name = "Home Phone Number")]
        //[RegularExpression(@"\d")]
        [DataType(DataType.PhoneNumber)]
        public Nullable<double> ParentHomePhoneNumber { get; set; }

        [Required]
        [Display(Name = "Parent Email Address")]
        [DataType(DataType.EmailAddress)]
        public string ParentEmailId { get; set; }

        [Required]
        [RegularExpression(@"\d{4,20}")]
        public string ORGID { get; set; }
    }
}

//namespace TestMVC001.Models
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class Student
//    {
//        public long StudentId { get; set; }
//        public string StudentFirstName { get; set; }
//        public string StudentMiddleName { get; set; }
//        public string StudentLastName { get; set; }
//        public string Class { get; set; }
//        public string Section { get; set; }
//        public string Gender { get; set; }
//        public Nullable<System.DateTime> DateOfBirth { get; set; }
//        public string RFID { get; set; }
//        public string ParentFirstName { get; set; }
//        public string ParentMiddleName { get; set; }
//        public string ParentLastName { get; set; }
//        public Nullable<double> ParentPrimaryPhoneNumber { get; set; }
//        public Nullable<double> ParentHomePhoneNumber { get; set; }
//        public string ParentEmailId { get; set; }
//        public string ORGID { get; set; }
//    }
//}
